apiVersion: apps/v1
kind: Deployment
metadata:
  name: asg-deployment
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asg
  template:
    metadata:
      labels:
        app: asg
    spec:
      containers:
        - name: asg
          image: 770424767729.dkr.ecr.ap-southeast-1.amazonaws.com/asg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: asg-service
  namespace: devsecops
spec:
  selector:
    app: asg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
